### ISSUE TITLE
Tests the new HTTP proxy configuration on a real envrionment

### ISSUE THREAD

**Issue by nmco** [geosolutions-it/MapStore2-C027#87]
@tdipisa one possibility is to test this on Comune di Firenze directly, is this possible?

**Comment by tdipisa** [comment]
Hi @nmco. Yes but, as reported by @offtherailz, we embed the http_proxy in MapStore using war plugin that mixes http_proxy and geostore into a single war file. The http_proxy is not included a as JAR but all .class files are included in WEB-INF/classes
Correct if I'm wrong @offtherailz and @nuno but I think the only way to test it in the client environment is to:
- merge the PR
- use the http_proxy master branch as a dependency for the MS project
- build the project and deploy the new MS war
- when tests are passed we can do a tag and release the new version to definitely use it for both Project and MS master (to be released in MS in the new major version)

**Comment by nmco** [comment]
I see, so yes you will need to do a full release of MapStore.

**Comment by nmco** [comment]
@offtherailz will check with @tdipisa the best approach to deploy the implemented enhancements on the client environment to test it.

**Comment by tdipisa** [comment]
@nmco @shadab-geo is there any new about the update of the geosolutions mvn repo with the updated artifact for geostore 1.6-SNAPSHOT and 1.7-SNAPSHOT?

**Comment by nmco** [comment]
@tdipisa what we panned was a release for:

- geostore 1.6.1, this one is done.
- http-proxy 1.2.0, will be done today

@shadab-geo will update the issue when its done.

**Comment by shadab-geo** [comment]
The http-proxy 1.2.0 release is done
@tdipisa @nmco

**Comment by tdipisa** [comment]
> @tdipisa what we panned was a release for:
> 
> * geostore 1.6.1, this one is done.
> * http-proxy 1.2.0, will be done today
> 
> @shadab-geo will update the issue when it is done.

@nmco what we planned is to test updates in the client environment before doing releases of http-proxy and geostore.

For http-proxy we can use master (1.2-SNAPSHOT) for testing new updates in the client project. The geosolutions mvn repo was already updated for this version.
But for geostore I was only waiting for 1.6-SNAPSHOT to be updated in mvn repo to be able to update the dependency in the client project and test it through a new build.

**Comment by nmco** [comment]
Understood @tdipisa, thx for the clarification, let's know if you need something else.

**Comment by tdipisa** [comment]
@nmco I'm sorry, we have 2 problems here:

1. I think a minor problem. The geostore-webapp/1.6.1 published [here](https://maven.geo-solutions.it/it/geosolutions/geostore/geostore-webapp/1.6.1/) includes SHAPSHOTS

![image](https://user-images.githubusercontent.com/1280027/153246492-850895c9-f133-4959-ab47-476e6f868e0c.png)

2. The major one. I've deployed the new project mapstore.war (after modifying the pom as reported [here](https://github.com/geosolutions-it/MapStore2-C027/pull/93/files#diff-06c528e8bf4bae607af1c54bfcfbb8f21c0d09a44cddb2851ffa08207dba3052)) and it seems the provided updates are not working (at least in the client environment). We have the same behavior as before. The http-proxy files seem to be up to date with new changes (they are the same reported [here](https://maven.geo-solutions.it/proxy/http_proxy/1.2.0/) in mvn repo):

![image](https://user-images.githubusercontent.com/1280027/153247357-b66bc27c-634b-49ea-b8b3-5b7797c26e48.png)

JAVA_OPTS we are using in the client environments are:

```
JAVA_OPTS="$JAVA_OPTS -Dhttp.proxyHost=proxyhttp.comune.intranet -Dhttp.proxyPort=8080 -Dhttps.proxyHost=proxyhttps.comune.intranet
-Dhttps.proxyPort=8080 -Dhttp.nonProxyHosts=\"*.comune.intranet|192.168.*|localhost\" -Dgeostore-ovr=${GEOSTORE_OVR} -Xms512M -Xmx1024M -server -XX:+UseParallelGC -Djava.awt.headless=true"
```

**Comment by nmco** [comment]
@shadab-geo I check the links provided by @tdipisa and indeed the release GeoStore WAR looks wrong.

Let's proceed like this:
1. Analyse what happen here, think about how o fix it.
2. How can we detect if proxy options are being handled, which logs shall we look for?

I have sent you an invitation for tomorrow so you can share with me your conclusion and we decide how to move forward.

### This is your TOP priority.

**Comment by tdipisa** [comment]
@nmco I am available to join the call if needed for a troubleshooting session.

**Comment by nmco** [comment]
Meeting minutes:
- Regarding the SNAPSHOT JARs included in GeoStore WAR:
  - The release is depending on 1.6-SNAPSHOT.
  - We should be using the[ project version](https://stackoverflow.com/questions/16895555/maven-managed-dependencies-resolving-project-version-from-parent-pom), please create an issue for this, and let's handle it later.
  - Now, release 1.6.1 is wrong and needs to be overridden in the artifactory.
  - But this, doesn't explain why the HTTP proxy is not working,
- Regarding the HTTP proxy:
  - We are asking the HTTP client to instantiate itself using the environment variables.
  - We need to understand and document it on the Wiki about how to enable [log4j2](https://logging.apache.org/log4j/2.x/manual/configuration.html) for the HTTP proxy project.

@shadab-geo fixed the GeoStore release, checked the login for an HTTP proxy, then start both GeoSetore v1.6.1 release locally and HTTP-proxy v1.2.0 locally to validate them, then let's have call.

**Comment by nmco** [comment]
Regarding the HTTP proxy non-host working, @shadab-geo possibly found the problem and will rais ea PR today.

**Comment by shadab-geo** [comment]
PR link: https://github.com/geosolutions-it/http-proxy/pull/60

**Comment by nmco** [comment]
Feedback for you @tdipisa:
- GeoStore 1.6.1 release amended, we recreated the TAG and overrode the artifacts in Maven.
- This [PR](https://github.com/geosolutions-it/http-proxy/pull/60) should fix the network proxy issue support, it is been merged and it's available on master.


Regarding the networking proxy support, it needs to be improved as I comment [HERE](https://github.com/geosolutions-it/http-proxy/pull/60#issuecomment-1040354604), but this should unblock you until we have time to properly fix it.

Le time know if you need something else form us.

**Comment by tdipisa** [comment]
@nmco I understand, thank you. I will create a new build of the MS project using the latest http-proxy (master) and the fixed 1.6.1 geostore release asap and I will let you know how it works on the client environment.

**Comment by tdipisa** [comment]
@nmco 

I've deployed a new war of MapStore using geostore 1.6.1 and http-proxy 1.3-SNAPSHOT as you indicated.

As far as the http-proxy is concerned all is working fine this round. I only noticed an issue connecting MS to the geoserver test balancer on _datigisnew.comune.intranet_ for WMS GetCapabilities, but I think it is an issue client side. I've reported it to the client via email and asked for a check. Therefore, I would like to wait for a client feedback before fixing the 1.2.0 release of http-proxy.

Anyway, I've noticed one thing that we need to fix for geostore 1.6.1. the first time I've deployed ne new MS war, MS did not start due to this error:

```
ERROR   2022-02-17 11:39:38.155   ContextLoader.initWebApplicationContext() - Context initialization failed
org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Failed to import bean definitions from URL location [classpa                                                                                th*:geostore-spring-security.xml]
Offending resource: URL [jar:file:/var/lib/tomcat9/webapps/mapstore2/WEB-INF/lib/geostore-rest-impl-1.6.1.jar!/applicationContext.xml]; nested exception is o                                                                                rg.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Duplicate <global-method-security> detected.
Offending resource: URL [file:/var/lib/tomcat9/webapps/mapstore2/WEB-INF/classes/geostore-spring-security.xml]
        at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:68)
        at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85)
        at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:76)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:19                                                                                2)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseDefaultElement(DefaultBeanDefinitionDocumentReader.java:147)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:132)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:93)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:493)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:143)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:178)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:149)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:124)
        at org.springframework.web.context.support.XmlWebApplicationContext.loadBeanDefinitions(XmlWebApplicationContext.java:93)
        at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:130)
        at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:467)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:397)
        at org.springframework.web.context.ContextLoader.createWebApplicationContext(ContextLoader.java:276)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:197)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:47)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4685)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5146)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:717)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:690)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:705)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:978)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1849)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at org.apache.catalina.startup.HostConfig.deployWARs(HostConfig.java:773)
        at org.apache.catalina.startup.HostConfig.deployApps(HostConfig.java:427)
        at org.apache.catalina.startup.HostConfig.start(HostConfig.java:1576)
        at org.apache.catalina.startup.HostConfig.lifecycleEvent(HostConfig.java:309)
        at org.apache.catalina.util.LifecycleBase.fireLifecycleEvent(LifecycleBase.java:123)
        at org.apache.catalina.util.LifecycleBase.setStateInternal(LifecycleBase.java:423)
        at org.apache.catalina.util.LifecycleBase.setState(LifecycleBase.java:366)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:936)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:841)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1384)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1374)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at org.apache.tomcat.util.threads.InlineExecutorService.execute(InlineExecutorService.java:75)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:134)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:909)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardService.startInternal(StandardService.java:421)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.core.StandardServer.startInternal(StandardServer.java:930)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:183)
        at org.apache.catalina.startup.Catalina.start(Catalina.java:633)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.catalina.startup.Bootstrap.start(Bootstrap.java:343)
        at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:478)
Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: Duplicate <global-method-security> detected.
Offending resource: URL [file:/var/lib/tomcat9/webapps/mapstore2/WEB-INF/classes/geostore-spring-security.xml]
        at org.springframework.beans.factory.parsing.FailFastProblemReporter.error(FailFastProblemReporter.java:68)
        at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:85)
        at org.springframework.beans.factory.parsing.ReaderContext.error(ReaderContext.java:72)
        at org.springframework.security.config.method.GlobalMethodSecurityBeanDefinitionParser.registerAdvisor(GlobalMethodSecurityBeanDefinitionParser.java:                                                                                333)
        at org.springframework.security.config.method.GlobalMethodSecurityBeanDefinitionParser.parse(GlobalMethodSecurityBeanDefinitionParser.java:212)
        at org.springframework.security.config.SecurityNamespaceHandler.parse(SecurityNamespaceHandler.java:86)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1335)
        at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1325)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:135)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:93)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:493)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:390)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:334)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:302)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:143)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:178)
        at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.importBeanDefinitionResource(DefaultBeanDefinitionDocumentReader.java:18                                                                                6)
        ... 59 more
```

Then I've checked in WEB-INF/lib and I found mixed dependencies that make me think there is something dirty in the geosolutions MVN repo:

![2022-02-17 11_44_19-lib](https://user-images.githubusercontent.com/1280027/154504146-abeb2976-f0d6-4d41-8809-09faf0a1d42d.png)

**Comment by nmco** [comment]
@taba90

**Comment by tdipisa** [comment]
@taba90 let me know if you need something from my side for this. We can meet shortly if you want.

**Comment by tdipisa** [comment]
@taba90 thank you. 

>@tdipisa the problem was in the artifacts pushed during the previous release process.
I've pushed them again after a clean local build and the duplicated dependencies are now gone.

I was imaging a problem like this indeed. Thank you again.

> Can you test it if it works for you as well?

I would like to do a final test including also these:
https://github.com/geosolutions-it/http-proxy/pull/63 (still to review)
https://github.com/geosolutions-it/http-proxy/pull/61 (already merged and testes locally by @offtherailz)

Therefore I prefer to wait for #63 to be merged to optimize the work and do a complete testing

**Comment by tdipisa** [comment]
@taba90 @ydeliorman 

I've deployed and successfully tested a MS instance including the latest http-proxy 1.3-SNAPSHOT that includes fixes made for the following:
https://github.com/geosolutions-it/http-proxy/issues/59 (and so https://github.com/geosolutions-it/http-proxy/pull/61)
https://github.com/geosolutions-it/MapStore2/issues/7862 (and so https://github.com/geosolutions-it/http-proxy/pull/63)

As I mentioned [here](https://github.com/geosolutions-it/http-proxy/issues/59#issuecomment-1047879420) the new updates for the http-proxy that are involving fixes for the [upgrade of the apache http client](https://github.com/geosolutions-it/http-proxy/commit/d408dba0e6439e00368d2114c46a7baf444fffbd) are expected to be backported until 1.2.x. 

So please @ydeliorman, backport all these fixes to 1.2.x and then amend the release 1.2.0. 1.2.0 will be used for the incoming MS release (@offtherailz).

**Comment by taba90** [comment]
@tdipisa backports will be performed by @shadab-geo that will take care to issue the new release as well. You should expect the new release to be available on friday.

**Comment by taba90** [comment]
@shadab-geo 
Summarizing we are going to backport 1.2.x:
- the work you did on master not still backported
- this commit https://github.com/geosolutions-it/http-proxy/commit/fcfb91ef95bfa84acb9c8d1c9018a204f2058b2b
- this commit https://github.com/geosolutions-it/http-proxy/commit/a90e548a57d4f448161131cbfeb90765e22e7e82

After backports are merged we are going to wait until @tdipisa gives us the green light that tests have been performed and are sucessfull.
Then we have to drop and recreate the tag 1.2.0 out of the updated 1.2.x branch.
Redo the release of 1.2.0.

**Comment by shadab-geo** [comment]
thanks @taba90

**Comment by shadab-geo** [comment]
@taba90 @tdipisa 
I have backported the changes to 1.2.x
PR: https://github.com/geosolutions-it/http-proxy/pull/64

**Comment by taba90** [comment]
@tdipisa  merged the backport on 1.2.x

**Comment by tdipisa** [comment]
Hi @taba90 thank you 
It seems the MVN repo still need to be updated with this, right?

**Comment by taba90** [comment]
yes I'll notify here when the repo is updated

**Comment by tdipisa** [comment]
Perfect, thank you @taba90.

**Comment by taba90** [comment]
@tdipisa repo updated

**Comment by tdipisa** [comment]
@taba90 I've tested and all is working properly it seems. Please redo the 1.2 version of http-proxy as agreed previously.

**Comment by taba90** [comment]
@tdipisa tomorrow morning @shadab-geo  will do the release.

**Comment by taba90** [comment]
@tdipisa http proxy 1.2.0 has been redone and pushed to the maven geosolutions repo.
