### ISSUE TITLE
Reported GeoFence issue to check

### ISSUE THREAD

**Issue by tdipisa** [geosolutions-it/MapStore2-C027#91]
From the client:

>come da indicazioni di Tobia, abbiamo provato a modificare le regole di geofence nuovo (http://sr-vm378-sitgfn:8080/geofence/) per poter gestire i wfs-t in sicurezza. Durante questi tentativi stiamo ottenendo un errore 500 (The call failed on the server), secondo una nostra prima analisi, questo errore potrebbe essere dovuto al valore instance presente che fa riferimento ai vecchi server sitgn1 e sitgn2 anche se sul nuovo geoserver vediamo i nuovi indirizzi.
Potete darci qualche indicazione a riguardo?

**Comment by tdipisa** [comment]
@randomorder I will do a first check.

**Comment by tdipisa** [comment]
Asked the client for steps to reproduce. I will check during the weekly status meeting.

**Comment by tdipisa** [comment]
```
10-Feb-2022 10:25:37.381 SEVERE [http-nio-8080-exec-6] org.apache.catalina.core.ApplicationContext.log Exception while dispatching incoming RPC call
        com.google.gwt.user.server.rpc.UnexpectedException: Service method 'public abstract void org.geoserver.geofence.gui.client.service.RulesManagerRemoteService.saveRule(org.geoserver.geofence.gui.client.model.RuleModel) throws org.>
                at com.google.gwt.user.server.rpc.RPC.encodeResponseForFailure(RPC.java:385)
                at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:588)
                at com.google.gwt.user.server.rpc.RemoteServiceServlet.processCall(RemoteServiceServlet.java:208)
                at com.google.gwt.user.server.rpc.RemoteServiceServlet.processPost(RemoteServiceServlet.java:248)
                at com.google.gwt.user.server.rpc.AbstractRemoteServiceServlet.doPost(AbstractRemoteServiceServlet.java:62)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
                at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.geoserver.geofence.gui.AuthenticationFilter.doFilter(AuthenticationFilter.java:39)
                at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
                at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
                at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
                at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
                at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
                at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
                at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
                at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:688)
                at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
                at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
                at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367)
                at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
                at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
                at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639)
                at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
                at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
                at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
                at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
                at java.lang.Thread.run(Thread.java:748)
        Caused by: org.springframework.dao.DataIntegrityViolationException: Could not execute JDBC batch update; SQL [insert into public.gf_rule (grant_type, ip_high, ip_low, ip_size, instance_id, layer, priority, request, rolename, ser>
                at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:259)
                at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:225)
                at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:521)
                at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:761)
                at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:730)
                at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:485)
                at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:291)
                at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
                at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
                at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:208)
                at com.sun.proxy.$Proxy64.persist(Unknown Source)
                at org.geoserver.geofence.services.RuleAdminServiceImpl.insert(RuleAdminServiceImpl.java:63)
                at org.geoserver.geofence.gui.server.service.impl.RulesManagerServiceImpl.saveRule(RulesManagerServiceImpl.java:189)
                at org.geoserver.geofence.gui.server.gwt.RulesManagerServiceImpl.saveRule(RulesManagerServiceImpl.java:75)
                at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
                at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.lang.reflect.Method.invoke(Method.java:498)
                at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:569)
                ... 30 more
        Caused by: org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
                at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:96)
                at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:66)
                at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:275)
				at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:268)
                at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:184)
                at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:321)
                at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:51)
                at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1216)
                at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:383)
                at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:133)
                at org.hibernate.ejb.TransactionImpl.commit(TransactionImpl.java:76)
                at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:517)
                ... 46 more
        Caused by: java.sql.BatchUpdateException: Batch entry 0 insert into public.gf_rule (grant_type, ip_high, ip_low, ip_size, instance_id, layer, priority, request, rolename, service, username, workspace, id) values ('DENY', NULL, N>
  Detail: Key (id)=(13) already exists.  Call getNextException to see other errors in the batch.
                at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:169)
                at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2286)
                at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:521)
                at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:870)
                at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:893)
                at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1644)
                at org.apache.commons.dbcp.DelegatingStatement.executeBatch(DelegatingStatement.java:297)
                at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:70)
                at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:268)
                ... 55 more
        Caused by: org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "gf_rule_pkey"
  Detail: Key (id)=(13) already exists.
                at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2553)
                at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2285)
                ... 62 more
```

**Comment by tdipisa** [comment]
@etj is currently doing a quick check on this.

**Comment by etj** [comment]
The id should be automatically set using a sequence, so there should not be id duplications.

One cause for this error may be that sequence and ids are unaligned (maybe a backup/restore procedure, where the seqs have not been properly migrated?)   
Please check that the sequence is properly aligned to the id in the related table -- i.e. `select max(id) from gf_rule` should be bigger than `select last_value from hibernate_sequence`.

Pls also consider that, as far as I can see in the [schema](https://github.com/geoserver/geofence/blob/3.5.x/doc/setup/sql/002_create_schema_postgres.sql), there is a single sequence that hibernate uses for all autoincremental fields.

**Comment by tdipisa** [comment]
> The id should be automatically set using a sequence, so there should not be id duplications.
> 
> One cause for this error may be that sequence and ids are unaligned (maybe a backup/restore procedure, where the seqs have not been properly migrated?) Please check that the sequence is properly aligned to the id in the related table -- i.e. `select max(id) from gf_rule` should be bigger than `select last_value from hibernate_sequence`.
> 
> Pls also consider that, as far as I can see in the [schema](https://github.com/geoserver/geofence/blob/3.5.x/doc/setup/sql/002_create_schema_postgres.sql), there is a single sequence that hibernate uses for all autoincremental fields.

@randomorder let me know when we can schedule this check next days

**Comment by lpasquali** [comment]
`select max(id) from gf_rule;` results in 130

`select last_value from hibernate_sequence;` results in 18

so maximum id value for table gf_rule is bigger than last value.
From what I see on the db yes, I confirm the id sequence is used in all the tables with id that are not empty (gf_user,gf_gsinstance)

@etj is there anything else I could check?

**Comment by etj** [comment]
The checks were needed in order to find out if the problem was in the sequence, and that's it indeed.

To fix this situation, the sequence value should be set to the max values of the id of any table.
So, consider `select max(id)` for each geofence table, the seq should be set as the highest in the `max(id)`s

**Comment by lpasquali** [comment]
@tdipisa @etj I successfully incremented the sequence, a backup was taken for tranquillity.
```
geofence=> select last_value from hibernate_sequence;
 last_value 
------------
        130
(1 row)

geofence=> select max(id) from gf_rule;
 max 
-----
 130
(1 row)

geofence=> 
```

**Comment by tdipisa** [comment]
@lpasquali thank you so much. I did a quick test using the GF UI and all seems working properly so far. I will ask the client to test again.
